# Project-wide Gradle settings.
# Specifies the JVM arguments used for the daemon process.
# Tăng RAM cho Gradle Daemon để build nhanh hơn
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# Bật song song build cho đa nhân CPU
org.gradle.parallel=true

# Bật Cache Build để không build lại những gì không thay đổi
org.gradle.caching=true

# Bật Configuration Cache giúp bỏ qua bước cấu hình Gradle chậm chạp mỗi lần chạy
org.gradle.configuration-cache=true

# Bật công cụ theo dõi file hệ thống để nhận diện thay đổi file nhanh hơn
org.gradle.vfs.watch=true

# AndroidX settings
android.useAndroidX=true

# Kotlin settings
kotlin.code.style=official
android.nonTransitiveRClass=true

# Tăng RAM cho Kotlin Daemon & Hỗ trợ build tăng trưởng (incremental)
kotlin.daemon.jvmargs=-Xmx2048m
kotlin.incremental=true
kapt.incremental.apt=true
kapt.use.worker.api=true