# Project-wide Gradle settings.
# Specifies the JVM arguments used for the daemon process.
# T?ng RAM cho Gradle Daemon ?? build nhanh h?n
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=512m -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# B?t song song build cho ?a nhân CPU
org.gradle.parallel=true

# B?t Cache Build ?? không build l?i nh?ng gì không thay ??i
org.gradle.caching=true

# B?t Configuration Cache giúp b? qua b??c c?u hình Gradle ch?m ch?p m?i l?n ch?y
org.gradle.configuration-cache=true

# B?t công c? theo dõi file h? th?ng ?? nh?n di?n thay ??i file nhanh h?n
org.gradle.vfs.watch=true

# AndroidX settings
android.useAndroidX=true

# Kotlin settings
kotlin.code.style=official
android.nonTransitiveRClass=true

# T?ng RAM cho Kotlin Daemon & H? tr? build t?ng tr??ng (incremental)
kotlin.daemon.jvmargs=-Xmx2048m
kotlin.incremental=true
kapt.incremental.apt=true
kapt.use.worker.api=true
org.gradle.java.home=C\:/Program Files/Java/jdk-21
