package com.example.finfit.finance.model

import com.google.firebase.Timestamp

enum class RecurringFrequency(val label: String) {
    DAILY("Hàng ngày"),
    WEEKLY("Hàng tuần"),
    MONTHLY("Hàng tháng"),
    YEARLY("Hàng năm")
}

/**
 * Giao dịch định kỳ (tiền điện nước, internet, tiền nhà, học phí, subscriptions Netflix/Spotify...)
 */
data class RecurringTransaction(
    val id: String = "",
    val name: String = "",
    val amount: Double = 0.0,
    val type: TransactionType = TransactionType.EXPENSE,
    val category: String = "Hóa đơn & Tiện ích",
    val accountId: String? = null,
    val frequency: RecurringFrequency = RecurringFrequency.MONTHLY,
    val dueDay: Int = 1, // Ngày trong tháng (1-31) hoặc thứ trong tuần (1-7)
    val isAutoGenerated: Boolean = false, // Tự động ghi vào lịch sử khi đến ngày
    val isActive: Boolean = true,
    val lastAppliedDate: Timestamp? = null,
    val note: String = ""
)
